### ISSUE TITLE
Can't open on arch with any terminal

### ISSUE THREAD

**Issue by jgc37** [diamondburned/6cord#5]
```
Missing token OR username and password!
panic: failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'

goroutine 1 [running]:
main.main()
        /home/jg3/6cord/main.go:146 +0x1f87
```

```
log file: 
2019/07/05 07:33:51 main.go:422: Storing token inside keyring...
2019/07/05 07:33:51 main.go:424: Failed to set keyring! Continuing anyway... fai
led to unlock correct collection '/org/freedesktop/secrets/aliases/default'    
2019/07/05 07:33:52 main.go:351: Discordgo: 0 2 [S0:CID1]: got close frame, code
: %d, Msg: %q [1002 ]                                                          
panic: exit status 1

goroutine 1 [running]:
main.main()
        /home/jg3/6cord/main.go:439 +0x1f0f
```

This happens in any terminal and with or without gnome-keyring installed

**Comment by diamondburned** [comment]
`Missing token OR username and password!`

Did you have `-t`?

**Comment by jgc37** [comment]
same error with -t 

```
goroutine 1 [running]:
main.main()
        /home/jg3/6cord/main.go:439 +0x1f0f
2019/07/05 21:07:50 main.go:422: Storing token inside keyring...
2019/07/05 21:07:50 main.go:424: Failed to set keyring! Continuing anyway... failed to unlock correct collection '/org/
freedesktop/secrets/aliases/default'                                                                                  
2019/07/05 21:07:53 main.go:351: Discordgo: 0 2 [S0:CID1]: got close frame, code: %d, Msg: %q [1002 ]
panic: exit status 1

```

**Comment by jgc37** [comment]
I fixed it by installing kde.  I was on i3 before.  Something about gnome-keyring needs a desktop environment for it to work I think.

**Comment by diamondburned** [comment]
Keyring should not be mandatory if a token is provided (and is not empty). This is something else.

**Comment by GwynethLlewelyn** [comment]
I know that this is an ancient issue, but to specifically fix the keyring issues (or get a workaround), maybe it's [worth taking a look at this issue on another package](https://github.com/zalando/go-keyring/issues/48).
